version: '3.9'
services:
      swagger-ui:
        image: swaggerapi/swagger-ui
        container_name: swagger_ui_container
        restart: always
        volumes:
          - ./doc:/usr/share/nginx/html/doc
        environment:
         API_URL: doc/swagger.json
         BASE_URL: /swagger
        ports:
          - "8080:8080"